name: ContainerAction
description: calculator to test contanier actions

inputs:
  number1:
    required: true
    default: "0"
  number2:
    required: true
    default: "0"

outputs:
  result:
    description: 'output os the sum of the two numbers'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.number1 }}
    - ${{ inputs.number2 }}
