name: artifacts

on:
  workflow_dispatch:

jobs:
  download-artifact:
    needs: upload-artifact
    name:  job to download-artifact
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Dispaly structure pf download files
        run: ls -R
      - run: cat myartifact.txt

  upload-artifact:
    name: upload-artifact
    runs-on: ubuntu-latest
    steps:
      - run: docker info > myartifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: myartifact.txt
          
