name: composite

on:
  workflow_dispatch:
jobs:
  composite-action:
    name: job to test composite action
    runs-on:  ubuntu-latest
    steps:
      -  uses:  actions/checkout@v4
      -  uses:  ./
         id:  compositeAction
         with:
           number1:  4
           number2:  6
      -  run:  echo ${{ steps.compositeAction.outputs.result }}
        
