name: variables and secrets

env:
  WF_VAR: "Workflow level variable"

on:
  workflow_dispatch:

jobs:
  test_variables:
    env:
      JOB_VAR: "job level variable"

    name: job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: test variables
        id:  stepVar
        env:
          STEP_VAR: "Step level variables"
        run: |
            echo ${{ github.actor }}
            echo $GITHUB_JOB
            echo $WF_VAR
            echo $JOB_VAR
            echo $STEP_VAR
            echo ${{ vars.CONF_VAR }}
            echo ${{ secrets.A_SECRET }}
